### ISSUE TITLE
Video is not autoplayed when clicking a slide

### ISSUE THREAD

**Issue by GhostOrder28** [holloway-ai/joan#62]
## Expected Behavior
When user clicks a slide then video player time should be changed to the slide's time and video should start playing.

## Current Behavior
When user clicks a slide then video player time is changed to the slide's time but video is not autoplayed.

## Steps to reproduce
1. Go to a video page.
2. Click some slide.
3. Video current time will be changed to the clicked slide but it will not be autoplayed.

## Notes
If user manually plays the video then the video is autoplayed as expected when user clicks others slides.

**Comment by iliatimofeev** [comment]
That's a feature. I changed Joan’s behavior. One click, just sync time. Double click toggles the play/pause state. Because auto sync while scrolling worked unexpectedly, I decided that sync on click would be a better solution.
